# Generated by Django 3.2.6 on 2021-08-05 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('domain', models.CharField(choices=[('HUBTEL', 'Hubtel'), ('THIRD_PARTY', 'Third Party')], max_length=20)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], max_length=20)),
                ('incident_status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], max_length=20)),
                ('problem', models.TextField(max_length=300)),
                ('resolution', models.TextField(max_length=300)),
                ('logged_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system_app', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logs.systemapps')),
            ],
        ),
    ]
