# Generated by Django 3.2.6 on 2021-08-06 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incidents',
            new_name='Incident',
        ),
        migrations.RenameModel(
            old_name='SystemApps',
            new_name='SystemApp',
        ),
    ]
