# Generated by Django 3.2.6 on 2021-08-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_incident_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
