# Generated by Django 3.2.6 on 2021-08-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_incident_incident_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='resolution',
            new_name='root_cause',
        ),
        migrations.AddField(
            model_name='incident',
            name='time_of_resolution',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
