# Generated by Django 3.2.6 on 2021-08-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_auto_20210806_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time_of_resolution',
            field=models.DateTimeField(null=True),
        ),
    ]
