# Generated by Django 3.2.6 on 2021-08-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20210806_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='domain',
            field=models.CharField(choices=[('Hubtel', 'Hubtel'), ('Third_Party', 'Third Party')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time_of_resolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemapp',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
