# Generated by Django 3.2.6 on 2021-08-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_remove_systemapp_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
