# Generated by Django 3.2.6 on 2021-08-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_incident_duration2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='duration2',
        ),
    ]
