# Generated by Django 3.2.6 on 2021-08-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_remove_incident_duration2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=18)),
                ('roles', models.CharField(choices=[('User', 'User')], max_length=10)),
                ('remember_token', models.CharField(max_length=200)),
            ],
        ),
    ]
